### ISSUE TITLE
SwaggerPlugin(serve_swagger_schema=False) causes exception

### ISSUE THREAD

**Issue by ereboschi** [cope-systems/bottle-swagger#8]
**Problem**:
Calling SwaggerPlugin with `serve_swagger_schema=False` causes an exception due to a bug in `SwaggerPlugin.__init__()`:

My Code:
```
        bottle.install(SwaggerPlugin(
            swagger_def=swagger_dict,
            serve_swagger_ui=True,
            swagger_ui_suburl='/swagger/',
            serve_swagger_schema=False))  # We want to serve swagger.json ourselves, so we can set host dynamically
```

Exception: `AttributeError: 'SwaggerPlugin' object has no attribute 'serve_swagger_ui'`

**Explanation**:
`SwaggerPlugin.__init__()`:
```
        ...
        self.serve_swagger_schema = serve_swagger_schema or self.serve_swagger_ui
        self.serve_swagger_ui = serve_swagger_ui
        ...
```

... `self.serve_swagger_ui` is undefined on the first line, because that value isn't set until the second line. Apparently, this isn't a problem for most people, because the default value of `serve_swagger_schema` is `True`, so the second half of the `or` statement is never evaluated (short-circuit).

This can be solved by changing the order of these lines. (Which would allow me to serve up `swagger.json` myself.)

**Comment by rpcope1** [comment]
Yes, I see, good catch. I'll see if I can't patch it in the next day or so and cut a new release. Thank you very much!

**Comment by ereboschi** [comment]
Sweet. Thank you.

**Comment by rpcope1** [comment]
@ereboschi I just cut a new release (2.0.6) that should fix the problem. Please let me know if this works on your end so that I can close the issue. Thanks!

**Comment by ereboschi** [comment]
Looks like 2.0.6 fixes the exception. Much obliged.

Unfortunately, I just discovered that the `SwaggerPlugin(serve_swagger_schema=False)` doesn't work if `serve_swagger_ui=True`... Bottle still serves up `/swagger.json` (because `self.serve_swagger_schema = serve_swagger_schema or serve_swagger_ui`)... but I can open a second bug for that.

Thank you.

**Comment by rpcope1** [comment]
That's rather embarrasing, then. I'll open a case and tag you in it, and I'll see if I can't cut another release with that fixed. Thank you so much for your patience.
